### ISSUE TITLE
How to pass function that returns gradient to Nonconvex.jl 

### ISSUE THREAD

**Issue by jonasmac16** [JuliaNonconvex/Nonconvex.jl#123]
Hi,
I am looking into linking `Nonconvex.jl` with `GalacticOptim.jl`. I was running into the issue that `GalacticOptim` takes care of the AD stuff for the optimisation problem but I couldn't see an easy way to pass this info into `Nonconvex.jl`. Is it possible or does the AD of the optimisation problem has to take place in `Nonconvex.jl`?

I hope my question is somewhat clear.

**Comment by mohdibntarek** [comment]
Define a new callable struct `GOFunction` that wraps a function and GO's AD-backend. Define a chain rule for `GOFunction` to make use of GO's AD mechanism. Nonconvex will be calling Zygote on the top level but that's a very shallow layer over GO's AD which can be using anything.

**Comment by mohdibntarek** [comment]
I am closing this now for lack of activity.

**Comment by jonasmac16** [comment]
Thanks for the pointer, I will have a try implementing this in the coming week. Do you mind if I tag you in the PR and get back to you if I have anymore questions?

**Comment by mohdibntarek** [comment]
Great, I don't mind at all!
