### ISSUE TITLE
Documentation Improvements for Model and Solutions Inspection 

### ISSUE THREAD

**Issue by ccoffrin** [JuliaNonconvex/Nonconvex.jl#133]
Here are some usage questions I have, which I could not find in the documentation.

Model inspection:
* best way to check the number of variables in the model?
* best way to check the number of constraints in the model?

Solution inspection (after the call to `Nonconvex.optimize` is complete):
* how to determine the status of the solver/algorithm, specifically did it claim to converge or not?
* how to inspect the values of the variables in the solution?
* how to determine the value of the objective function at the solution point?

Answers would be helpful and I would recommend add some examples to the documentation.

**Comment by mohdibntarek** [comment]
>best way to check the number of variables in the model?

`Nonconvex.NonconvexCore.getnvars(model)`

>best way to check the number of constraints in the model?

`Nonconvex.NonconvexCore.getnconstraints(model)`

>how to determine the status of the solver/algorithm, specifically did it claim to converge or not?

Different wrappers are different. For Ipopt, the output of `optimize` has a field `status` which is the solver status returned from `Ipopt.IpoptSolve`.

> how to inspect the values of the variables in the solution?

`result.minimizer`

> how to determine the value of the objective function at the solution point?

`result.minimum`

> Answers would be helpful and I would recommend add some examples to the documentation.

I am working on an improvement of the docs. Of course, PRs with the above answers would be welcome as well :)

**Comment by mohdibntarek** [comment]
The latest docs address these issues.
