### ISSUE TITLE
Jacobian_Approximation for IPOPT

### ISSUE THREAD

**Issue by bdas123** [JuliaNonconvex/Nonconvex.jl#135]
What is the argument to use the argument "jacobian_approximation" for IPOPT within Nonconvex.jl?

**Comment by mohdibntarek** [comment]
By default Nonconvex uses the l-BFGS approximation of the Hessian. It's not Jacobian approximation though. To compute and use the Hessian using autodiff, set the `first_order` option to `false`. Check the docs for more details.
