### ISSUE TITLE
Workaround for Mutating Arrays

### ISSUE THREAD

**Issue by bdas123** [JuliaNonconvex/Nonconvex.jl#137]
Just out of curiosity, are there any workarounds for the "cannot handle mutating arrays" issue?

I'd like to know what has already worked in the past.

**Comment by mohdibntarek** [comment]
1. Use AD packages other than Zygote, e.g. ForwardDiff and ReverseDiff
2. Define an rrule using ChainRulesCore for your mutating function if it's simple enough to derive
3. Avoid pre-allocation and use a non-mutating version of functions, e.g. use:
```julia
y = map(1:3) do i
  x[i]^2
end
```
instead of:
```julia
y = similar(x)
for i in 1:3
  y[i] = x[i]^2
end
```

**Comment by bdas123** [comment]
Is there documentation for going about the first option?

Since Nonconvex.jl is built on Zygote.jl, how do I specify to use ForwardDiff instead?

**Comment by mohdibntarek** [comment]
Check the docs of the latest release https://julianonconvex.github.io/Nonconvex.jl/stable/gradients/other_ad/.

**Comment by mohdibntarek** [comment]
I will consider this issue solved.
