### ISSUE TITLE
Extract number of iterations from results

### ISSUE THREAD

**Issue by bdas123** [JuliaNonconvex/Nonconvex.jl#150]
Is there a way to extract the number of iterations from the results?

**Comment by mohdibntarek** [comment]
Wrap the objective function with
```julia
obj = Nonconvex.NonconvexCore.CountingFunction(f)
```
and use `obj` as the objective function. The number of times it's evaluated will be `obj.counter[]`.

**Comment by bdas123** [comment]
Is there any way to also extract the number of function evaluations and the number of gradient evaluations?
