### ISSUE TITLE
Problem with sparse matrix when using CustomGradFunction

### ISSUE THREAD

**Issue by bdas123** [JuliaNonconvex/Nonconvex.jl#152]
I get the following error 

`no method matching sparse(::Float64)`

when I use the following code

```
jacobian = CustomGradFunction(calc_sse, calc_der)
model = Model(jacobian)
addvar!(model, zeros(540), zeros(540).+500, init = x0)
alg = NLoptAlg(:LD_MMA)
options = NLoptOptions(ftol_rel = 1e-6)
@time result = optimize(model, alg, x0, options = options)
```

The functions calc_sse and calc_der work fine as is.

**Comment by mohdibntarek** [comment]
Make sure `calc_der` returns a vector. If there is only 1 variable, it should be a vector of length 1.

**Comment by mohdibntarek** [comment]
It should be a vector of length 540 in this case it seems.
