### ISSUE TITLE
Example of Changing AD Package

### ISSUE THREAD

**Issue by bdas123** [JuliaNonconvex/Nonconvex.jl#156]
Can you provide a sample code that changes the AD package from Zygote to something else?

The current documentation is unclear: https://julianonconvex.github.io/Nonconvex.jl/stable/gradients/other_ad/#Using-other-AD-packages

**Comment by mohdibntarek** [comment]
check https://github.com/JuliaNonconvex/NonconvexUtils.jl/blob/main/test/abstractdiff.jl for examples and feel free to contribute to the documentation :)

**Comment by mohdibntarek** [comment]
line 104 onwards
