### ISSUE TITLE
Unified API for information of the results

### ISSUE THREAD

**Issue by AlCap23** [JuliaNonconvex/Nonconvex.jl#159]
It would be nice to get an API to get information like the Lagrange Multiplier out of the result. 

Given that each algorithm implements its own return types, this would be needed to go into Core and spread onwards from there on.

@mohamed82008 would that be a valid feature request?

**Comment by mohdibntarek** [comment]
For some solvers it is valid. For others, that don't provide the Lagrangian multipliers, we will have to throw an error.
