### ISSUE TITLE
Last Number in NLopt Result is Iterations or Function Evaluations?

### ISSUE THREAD

**Issue by bdas123** [JuliaNonconvex/Nonconvex.jl#164]
I used the NLopt sublibrary of Nonconvex.jl and flawlessly produced this result (thanks!). 

Does the 7 at the end refer to the number of iterations or the number of function evaluations?

`(24.803576195514637, [0.0034268698816598115, 0.0034167874306103153, 0.003422486762726054, 0.003436397782093415, 0.003433135515691, 0.003430665420839997, 0.0035616063238203583, 0.003433791603979608, 0.0034297241253756945, 0.003430012088655871  …  0.002748720869350672, 0.009841704735863552, 0.0002592440481656402, 0.0008748455873136366, 0.005675712242591848, 0.0013491389987927238, 0.0026657436746096988, 0.0012880692189073033, 0.010187046681556974, 0.0011754704851364825], NonconvexNLopt.NLoptResult{Vector{Float64}, Float64, NLopt.Opt, Symbol, NLoptAlg{Nothing}, NLoptOptions{NamedTuple{(:suboptions, :ftol_rel, :ftol_abs, :xtol_rel, :xtol_abs), Tuple{NLoptOptions{NamedTuple{(), Tuple{}}}, Float64, Float64, Float64, Float64}}}, Int64}([0.0034268698816598115, 0.0034167874306103153, 0.003422486762726054, 0.003436397782093415, 0.003433135515691, 0.003430665420839997, 0.0035616063238203583, 0.003433791603979608, 0.0034297241253756945, 0.003430012088655871  …  0.002748720869350672, 0.009841704735863552, 0.0002592440481656402, 0.0008748455873136366, 0.005675712242591848, 0.0013491389987927238, 0.0026657436746096988, 0.0012880692189073033, 0.010187046681556974, 0.0011754704851364825], 24.803576195514637, Opt(LD_LBFGS, 2979), :XTOL_REACHED, NLoptAlg{Nothing}(:LD_LBFGS, nothing), NLoptOptions{NamedTuple{(:suboptions, :ftol_rel, :ftol_abs, :xtol_rel, :xtol_abs), Tuple{NLoptOptions{NamedTuple{(), Tuple{}}}, Float64, Float64, Float64, Float64}}}((suboptions = NLoptOptions{NamedTuple{(), Tuple{}}}(NamedTuple()), ftol_rel = 0.001, ftol_abs = 1.0e-6, xtol_rel = 1.0e-6, xtol_abs = 1.0e-6)), 7))`

**Comment by mohdibntarek** [comment]
Hey! Sorry I just saw this issue. Yes the 7 is the number of times the functions were evaluated.

**Comment by mohdibntarek** [comment]
Not the number of iterations

**Comment by mohdibntarek** [comment]
Closing this issue. Feel free to open another issue and ping me if you have more questions.
