### ISSUE TITLE
failed to precompile Nonconvex

### ISSUE THREAD

**Issue by jmartfrut** [JuliaNonconvex/Nonconvex.jl#165]
Hello, I'm using GridapEmbedded package and when I add Nonconvex to my project I receive an error due to failed precompilation. It seems to be any conflict between this two packages. I am using Mac, I would appreciate it if you could help me with some advice.

**Comment by mohdibntarek** [comment]
This PR https://github.com/gridap/GridapEmbedded.jl/pull/75 fixes your issue on my machine. Please test it and let me know.

**Comment by jmartfrut** [comment]
Thanks @mohamed82008 for your fast reply. The changes in this PR solve some precompilation problems (e.g. miniQhull and GridapEmbedded) but still having the following sequence of failures:

✗ SymbolicUtils
✗ Symbolics
✗ SparseDiffTools → SparseDiffToolsSymbolicsExt
X NonconvexUtils
X Nonconvex

**Comment by mohdibntarek** [comment]
try adding the latest Nonconvex 2.1.3

**Comment by jmartfrut** [comment]
Hi @mohamed82008,  I have started a brand new project and added these two packages

 GridapEmbedded v0.8.2
 Nonconvex v2.1.3

I can precompile both packages separately but having the same precompilation issues when both are together. My 
versioninfo is 

Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (x86_64-apple-darwin22.4.0)
  CPU: 16 × Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
  Threads: 1 on 16 virtual cores

**Comment by mohdibntarek** [comment]
This works for me in a new environment. Note that you need to use the PR branch in GridapEmbedded until it gets merged.
```julia
import Pkg
Pkg.add(url = "https://github.com/mohamed82008/GridapEmbedded.jl", rev = "patch-1")
Pkg.add("Nonconvex")
using Nonconvex, GridapEmbedded
```

```julia
julia> Pkg.status()
Status `~/../Project.toml`
  [8838a6a3] GridapEmbedded v0.8.2 `https://github.com/mohamed82008/GridapEmbedded.jl#patch-1`
  [01bcebdf] Nonconvex v2.1.3
```

**Comment by jmartfrut** [comment]
Thank you @mohamed82008, the issue is solved. 👍
