### ISSUE TITLE
MathOptInterface and MINLP

### ISSUE THREAD

**Issue by mohdibntarek** [JuliaNonconvex/Nonconvex.jl#26]
We should be able to convert a Nonconvex model to a MathOptInterface model. An example of how to do this can be found in https://github.com/jump-dev/MathOptInterface.jl/blob/77799c6009cad302ea5b638ff0460ea0af119835/src/Test/nlp.jl. Then if we can specify integer variables in Nonconvex, we can convey this information to MOI and use Juniper or Pavito together with Ipopt for MINLP.

**Comment by matbesancon** [comment]
Other biased suggestion: SCIP supports MINLPs (with common non-linear functions)

**Comment by mohdibntarek** [comment]
Ya SCIP would be great to have. Note that I already connected Nonconvex with MOI. It's just not documented yet and there is no way to specify integer variables yet in Nonconvex. But I test Juniper + Ipopt on a Nonconvex model in https://github.com/mohamed82008/Nonconvex.jl/blob/master/test/juniper.jl.

**Comment by mohdibntarek** [comment]
Supporting expression-baed NLP and MINLP will be done using ModelingToolkit to reverse-engineer the function to get the expression. See #36.

**Comment by mohdibntarek** [comment]
MINLP is now available via Juniper. See the README for an example. Closing this issue. I opened 2 issues for SCIP and Pavito.
