### ISSUE TITLE
Useage with ComponentArrays

### ISSUE THREAD

**Issue by AlCap23** [JuliaNonconvex/Nonconvex.jl#99]
Thanks for the nice package! 

I was wondering if it is possible to build a `Model` using ComponentArrays, and if not what would be needed to do so. 
This would be especially useful for larger models with some kind of underlying structure. I also tried a `NamedTuple`, but maybe I am getting the concept of the constraint wrong here.

A MWE that does not work for me
```julia
using LinearAlgebra
using Nonconvex
using ComponentArrays

# Lower bound
p_lb = ComponentArray(
    qs = zeros(30),
    a = 1.0
)

# Upper Bound
p_ub = ComponentArray(
    qs = ones(30),
    a = 1.0
)

m = Model()
set_objective!(m, p->sum(abs2, p))

# Works fine
addvar!(m, p_lb, p_ub)

# Define inequality constraint
upper_bounds(p) = vec(p.qs) .- 1

upper_bounds(p_ub)

add_ineq_constraint!(m, upper_bounds)
```
Returns `type Array has no field qs`.  I tried tracing the error, but got stuck in the `add_ineq_constraint!` method. If there is a quick PR to fix this, I would be happy to help :smiley:

**Comment by mohdibntarek** [comment]
Hi @AlCap23! Thanks for your kind words. This should work with named tuples already.
```julia
using LinearAlgebra
using Nonconvex

# Lower bound
p_lb = (qs = zeros(30), a = 1.0)

# Upper Bound
p_ub = (qs = ones(30), a = 2.0)

m = Model()
set_objective!(m, p->sum(norm, p))

# Works fine
addvar!(m, p_lb, p_ub)

x0 = (qs = fill(0.5, 30), a = 1.5)
res = optimize(m, IpoptAlg(), x0)
```

I changed the abs2 to norm because abs2 is not defined for vectors.

**Comment by agerlach** [comment]
I am facing similar issues to @AlCap23 . @mohamed82008 , what you posted works fine, but not if you have a constraints. 

```julia
using LinearAlgebra
using Nonconvex

# Lower bound
p_lb = (qs = zeros(30), a = 1.0)

# Upper Bound
p_ub = (qs = ones(30), a = 2.0)

m = Model()
set_objective!(m, p->sum(norm, p))

# Works fine
addvar!(m, p_lb, p_ub)
add_eq_constraint!(m, x->x.qs) # ERROR: type Array has no field qs
```

**Comment by mohdibntarek** [comment]
The decision variable is a vector of one element which is a named tuple. So you actually need:
```julia
set_objective!(m, p->sum(norm, p[1]))
add_eq_constraint!(m, x -> x[1].qs)
```
I made a mistake above but `norm` was defined for a named tuple so the mistake wasn't obvious.

**Comment by agerlach** [comment]
Changing to 
```julia
add_eq_constraint!(m, x->x[1].qs)
```
allows you to add the constraint. However, the `optimize` call then fails w/ `Error: type Array has no field qs`. Adding a dummy variable seems to get around it.

```julia
using LinearAlgebra
using Nonconvex

# Lower bound
p_lb = (qs = zeros(30), a = 1.0)

# Upper Bound
p_ub = (qs = ones(30), a = 2.0)

m = Model()
set_objective!(m, p->sum(norm, p))

# Works fine
addvar!(m, p_lb, p_ub)
addvar!(m, [1.0], [5.0]) # dummy
add_eq_constraint!(m, x->x[1].qs)

x0 = (qs = fill(0.5, 30), a = 1.5)
res = optimize(m, IpoptAlg(), (x0, 2.0))
```

**Comment by mohdibntarek** [comment]
You want to use:
```julia
using LinearAlgebra
using Nonconvex

# Lower bound
p_lb = (qs = zeros(30), a = 1.0)

# Upper Bound
p_ub = (qs = ones(30), a = 2.0)

m = Model()
set_objective!(m, p->sum(norm, p[1]))

# Works fine
addvar!(m, p_lb, p_ub)
add_eq_constraint!(m, x->x[1].qs)

x0 = [(qs = fill(0.5, 30), a = 1.5)]
res = optimize(m, IpoptAlg(), x0)
```

Or

```julia
p_lb = (qs = zeros(30), a = 1.0)
p_ub = (qs = ones(30), a = 2.0)
m = Model()
set_objective!(m, p->sum(norm, p[1]))
addvar!(m, p_lb, p_ub)
addvar!(m, [1.0], [5.0]) # dummy
add_eq_constraint!(m, x->x[1].qs)
x0 = (qs = fill(0.5, 30), a = 1.5)
res = optimize(m, IpoptAlg(), [x0, 2.0])
```
Note I changed the tuple to array at the end.

**Comment by mohdibntarek** [comment]
@agerlach Please contribute to the docs in case it's not clear enough https://mohamed82008.github.io/Nonconvex.jl/stable/problem/#Variable-definition.

**Comment by mohdibntarek** [comment]
Closing this since the issue seems to be inactive and the `DictModel` largely avoids the need of `ComponentArrays`.
